{
	"version": 1561274291,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/bird-sheet0.png",
		"images/bird-sheet1.png",
		"images/tiledbackground.png",
		"images/tiledbackground2.png",
		"images/background-sheet0.png",
		"images/bottompipe-sheet0.png",
		"images/toppipe-sheet0.png",
		"images/bg-sheet0.png",
		"images/playsprite-sheet0.png",
		"images/ammo-sheet0.png",
		"images/emmy-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/box-sheet0.png",
		"images/trip-sheet0.png",
		"images/star-sheet0.png",
		"images/star1-sheet0.png",
		"images/hearth-sheet0.png",
		"images/scorestar-sheet0.png",
		"images/win-sheet0.png",
		"images/replay-sheet0.png",
		"images/images-sheet0.png",
		"images/ex-sheet0.png",
		"images/ex-sheet1.png",
		"images/ex-sheet2.png",
		"media/oooscary1.m4a",
		"media/oooscary1.ogg",
		"media/squaremotif1.m4a",
		"media/squaremotif1.ogg",
		"media/explosion 3.m4a",
		"media/explosion 3.ogg",
		"media/mattoglseby - 2.m4a",
		"media/mattoglseby - 2.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}