{
	"version": 1564904375,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"images/bg-sheet0.png",
		"images/bg1-sheet0.png",
		"images/gm1.png",
		"images/gr1-sheet0.png",
		"images/ggr-sheet0.png",
		"images/ggl-sheet0.png",
		"images/gl1-sheet0.png",
		"images/player-sheet0.png",
		"images/score-sheet0.png",
		"images/bscore-sheet0.png",
		"images/blive-sheet0.png",
		"images/btime-sheet0.png",
		"images/e1-sheet0.png",
		"images/weed-sheet0.png",
		"images/dwin-sheet0.png",
		"images/ar-sheet0.png",
		"images/winn-sheet0.png",
		"images/bwin1-sheet0.png",
		"images/nextto-sheet0.png",
		"images/nextto2-sheet0.png",
		"images/nextto3-sheet0.png",
		"images/bb-sheet0.png",
		"images/bb2-sheet0.png",
		"images/mbg1-sheet0.png",
		"images/boardd-sheet0.png",
		"images/bplay-sheet0.png",
		"images/sprite-sheet0.png",
		"images/gg2.png",
		"images/gg3r-sheet0.png",
		"images/gg3l-sheet0.png",
		"images/up1r-sheet0.png",
		"images/up2l-sheet0.png",
		"images/up3-sheet0.png",
		"images/up-sheet0.png",
		"images/bgbg1-sheet0.png",
		"images/bgbgbg2-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/winn2-sheet0.png",
		"images/sprite4-sheet0.png",
		"media/กระโดด.m4a",
		"media/กระโดด.ogg",
		"media/โดนมอน.m4a",
		"media/โดนมอน.ogg",
		"media/sfx1.m4a",
		"media/sfx1.ogg",
		"media/upgrade1.m4a",
		"media/upgrade1.ogg",
		"media/mattoglseby - 3.m4a",
		"media/mattoglseby - 3.ogg",
		"media/mattoglseby - 1.m4a",
		"media/mattoglseby - 1.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}