{
	"version": 1561276415,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/quiz-sheet0.png",
		"images/game-sheet0.png",
		"images/btnhome-sheet0.png",
		"images/bg-sheet0.png",
		"images/ground.png",
		"images/ston.png",
		"images/coin-sheet0.png",
		"images/cloud-sheet0.png",
		"images/lion-sheet0.png",
		"images/bggameover-sheet0.png",
		"images/btnreplay-sheet0.png",
		"images/win-sheet0.png",
		"images/btnhomegame-sheet0.png",
		"images/stow-sheet0.png",
		"images/speaker-sheet0.png",
		"images/speaker-sheet1.png",
		"images/apple-sheet0.png",
		"images/031720x-sheet0.png",
		"images/play-sheet0.png",
		"images/61465408_2298225857085540_6649895364725833728_n-sheet0.png",
		"media/correct.m4a",
		"media/correct.ogg",
		"media/lose.m4a",
		"media/lose.ogg",
		"media/pickup coin.m4a",
		"media/pickup coin.ogg",
		"media/bgloop.m4a",
		"media/bgloop.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}