{
	"version": 1560068264,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/ground-sheet0.png",
		"images/player-sheet0.png",
		"images/gun-sheet0.png",
		"images/bg_laygut1-sheet0.png",
		"images/light-sheet0.png",
		"images/start_button-sheet0.png",
		"images/bullet-sheet0.png",
		"images/ground_dead-sheet0.png",
		"images/restart-sheet0.png",
		"images/enemy-sheet0.png",
		"images/enemy2-sheet0.png",
		"images/ground_layout3-sheet0.png",
		"images/bg_layout3-sheet0.png",
		"images/bg_deadscene-sheet0.png",
		"images/afterlife_door-sheet0.png",
		"images/boss-sheet0.png",
		"images/boss-sheet1.png",
		"images/boss-sheet2.png",
		"images/platform-sheet0.png",
		"media/scary maze game face and sound (1).m4a",
		"media/scary maze game face and sound (1).ogg",
		"media/scary face with scream.m4a",
		"media/scary face with scream.ogg",
		"media/scary dark background music ambient (1).m4a",
		"media/scary dark background music ambient (1).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}