{
	"version": 1560068174,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/tiledbackground.png",
		"images/player-sheet0.png",
		"images/player-sheet1.png",
		"images/healthbar-sheet0.png",
		"images/healthbar2-sheet0.png",
		"images/healthbar2-sheet1.png",
		"images/healthbar2-sheet2.png",
		"images/ground-sheet0.png",
		"images/spritefont.png",
		"images/infectedscreen-sheet0.png",
		"images/barrel-sheet0.png",
		"images/bullet-sheet0.png",
		"images/portal-sheet0.png",
		"images/boom-sheet0.png",
		"images/boom-sheet1.png",
		"images/boom-sheet2.png",
		"images/zombie-sheet0.png",
		"images/solid-sheet0.png",
		"images/poref-sheet0.png",
		"images/godgun-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"media/ok - 1.m4a",
		"media/ok - 1.ogg",
		"media/brush 5.m4a",
		"media/brush 5.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}