{
	"version": 1564903073,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"images/player1-sheet0.png",
		"images/player1-sheet1.png",
		"images/player1-sheet2.png",
		"images/ground1-sheet0.png",
		"images/block1-sheet0.png",
		"images/sprite-sheet0.png",
		"images/ground2-sheet0.png",
		"images/cost-sheet0.png",
		"images/die1-sheet0.png",
		"images/reset-sheet0.png",
		"images/box1-sheet0.png",
		"images/ground.png",
		"images/die2-sheet0.png",
		"images/run-sheet0.png",
		"images/block4-sheet0.png",
		"images/run2-sheet0.png",
		"media/mattoglseby - 1.m4a",
		"media/mattoglseby - 1.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}