{
	"version": 1561277309,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/player-sheet0.png",
		"images/player-sheet1.png",
		"images/ground-sheet0.png",
		"images/tree-sheet0.png",
		"images/apple-sheet0.png",
		"images/enermy-sheet0.png",
		"images/life-sheet0.png",
		"images/box-sheet0.png",
		"images/replay-sheet0.png",
		"images/sakura-sheet0.png",
		"images/frame-sheet0.png",
		"images/sakuras-sheet0.png",
		"images/house-sheet0.png",
		"images/houseg-sheet0.png",
		"images/block-sheet0.png",
		"images/seven-sheet0.png",
		"images/object-sheet0.png",
		"images/sprite-sheet0.png",
		"images/title-sheet0.png",
		"images/lose-sheet0.png",
		"images/background-sheet0.png",
		"media/super mario bros.-coin sound effect (1).m4a",
		"media/super mario bros.-coin sound effect (1).ogg",
		"media/snow - katana zero (gamerip) (1).m4a",
		"media/snow - katana zero (gamerip) (1).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}