{
	"version": 1561274817,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/playb-sheet0.png",
		"images/player-sheet0.png",
		"images/bullet-sheet0.png",
		"images/enemy-sheet0.png",
		"images/panal-sheet0.png",
		"images/replay-sheet0.png",
		"images/player2-sheet0.png",
		"images/space-sheet0.png",
		"images/ex-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"media/explosion 3.m4a",
		"media/explosion 3.ogg",
		"media/mattoglseby - 1.m4a",
		"media/mattoglseby - 1.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}