{
	"version": 1564902457,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"images/bg-sheet0.png",
		"images/bg2-sheet0.png",
		"images/bg3-sheet0.png",
		"images/bg4-sheet0.png",
		"images/bg5-sheet0.png",
		"images/bg6-sheet0.png",
		"images/bg7-sheet0.png",
		"images/player-sheet0.png",
		"images/ground-sheet0.png",
		"images/win-sheet0.png",
		"images/block-sheet0.png",
		"images/mon-sheet0.png",
		"images/mon2-sheet0.png",
		"images/bonus-sheet0.png",
		"images/reset-sheet0.png",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}