{
	"version": 1566718497,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/tiledbackground.png",
		"images/sky-sheet0.png",
		"images/tiledbackground3.png",
		"images/tiledbackground4.png",
		"images/tiledbackground5.png",
		"images/tiledbackground6.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/player-sheet0.png",
		"images/player-sheet1.png",
		"images/player-sheet2.png",
		"images/blocks-sheet0.png",
		"images/particles.png",
		"images/em-sheet0.png",
		"images/em2-sheet0.png",
		"images/blocks3.png",
		"images/sprite11-sheet0.png",
		"images/tiledbackground8.png",
		"images/life-sheet0.png",
		"images/life-sheet1.png",
		"images/blocks2.png",
		"images/f2.png",
		"images/f-sheet0.png",
		"images/coin-sheet0.png",
		"images/box-sheet0.png",
		"images/bullet-sheet0.png",
		"images/particles2.png",
		"images/particles3.png",
		"images/djump-sheet0.png",
		"images/djump-sheet1.png",
		"images/sprite6-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/tiledbackground7.png",
		"images/sprite8-sheet0.png",
		"images/sprite9-sheet0.png",
		"images/sprite14-sheet0.png",
		"images/sprite17-sheet0.png",
		"images/sprite18-sheet0.png",
		"images/sprite21-sheet0.png",
		"media/game_over.ogg",
		"media/player_shot.ogg",
		"media/bonus_destroy.ogg",
		"media/bonus_points.ogg",
		"media/drumming sticks.ogg",
		"media/mattoglseby - 1.m4a",
		"media/mattoglseby - 1.ogg",
		"media/mattoglseby - 2.m4a",
		"media/mattoglseby - 2.ogg",
		"media/mattoglseby - 3.m4a",
		"media/mattoglseby - 3.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}