{
	"version": 1561276068,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/playbutton-sheet0.png",
		"images/bg-sheet0.png",
		"images/gruond-sheet0.png",
		"images/player-sheet0.png",
		"images/bullet-sheet0.png",
		"images/enemy-sheet0.png",
		"images/bg2-sheet0.png",
		"images/jump-sheet0.png",
		"images/star-sheet0.png",
		"images/qiuz-sheet0.png",
		"images/maxresdefault-sheet0.png",
		"images/replay-sheet0.png",
		"images/hearth-sheet0.png",
		"images/a-sheet0.png",
		"images/b-sheet0.png",
		"media/ricochet 1.m4a",
		"media/ricochet 1.ogg",
		"media/yv-back-in-time-_ncs-release_.m4a",
		"media/yv-back-in-time-_ncs-release_.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}