{
	"version": 1560067901,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/player-sheet0.png",
		"images/enemy-sheet0.png",
		"images/enemy-sheet1.png",
		"images/enemy-sheet2.png",
		"images/enemy-sheet3.png",
		"images/walkground.png",
		"images/bullet-sheet0.png",
		"images/slope-sheet0.png",
		"images/leftbutton-sheet0.png",
		"images/rightbutton-sheet0.png",
		"images/upbutton-sheet0.png",
		"images/shootbutton-sheet0.png",
		"images/coin-sheet0.png",
		"images/bg.png",
		"images/lift-sheet0.png",
		"images/slope2-sheet0.png",
		"images/door-sheet0.png",
		"images/block-sheet0.png",
		"images/block2.png",
		"images/blockright-sheet0.png",
		"images/blockright2-sheet0.png",
		"images/reset-sheet0.png",
		"media/alpha dance.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}