{
	"version": 1560068173,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/sprite-sheet0.png",
		"images/ground.png",
		"images/ทางชันขวา-sheet0.png",
		"images/ทางชีนซ้าย-sheet0.png",
		"images/player-sheet0.png",
		"images/bullet2-sheet0.png",
		"images/explosion-sheet0.png",
		"images/enemy-sheet0.png",
		"images/enemy-sheet1.png",
		"images/door-sheet0.png",
		"images/enemy2-sheet0.png",
		"images/player2-sheet0.png",
		"images/player2-sheet1.png",
		"images/bullet3-sheet0.png",
		"images/bullet3-sheet1.png",
		"images/bullet3-sheet2.png",
		"images/explosion2-sheet0.png",
		"images/explosion3-sheet0.png",
		"media/clock.m4a",
		"media/clock.ogg",
		"media/death.m4a",
		"media/death.ogg",
		"media/powerfull.m4a",
		"media/powerfull.ogg",
		"media/ricochet 1.m4a",
		"media/ricochet 1.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}